apiVersion: v1
kind: Secret
metadata:
  name: peer-pods-secret
  namespace: openshift-sandboxed-containers-operator
type: Opaque
stringData:
  # CLOUD_PROVIDER: "libvirt"
  # LIBVIRT_URI: "qemu+ssh://root@192.168.122.1/system?no_verify=1"
  # LIBVIRT_NET: "default
  # LIBVIRT_POOL: "default"
  # LIBVIRT_IMAGE_TYPE: "pre-built" // "pre-built" can be any image.
  # LIBVIRT_IMAGE_SOURCE: "icr.io/coco/hpcc:v1" 
  # LIBVIRT_PODVM_IMAGE_PATH: "/image/libvirt-coco.qcow2"
