apiVersion: v1
kind: ConfigMap
metadata:
  name: libvirt-podvm-image-cm
  namespace: openshift-sandboxed-containers-operator
data:
  HPCC_PODVM_IMAGE: "quay.io/ajvictor/podvm-libvirt-rhel-s390x"
  ENABLE_HP: "true"

