apiVersion: v1
kind: ConfigMap
metadata:
  name: libvirt-podvm-image-cm
  namespace: openshift-sandboxed-containers-operator
data:
  LIBVIRT_IMAGE_TYPE: "pre-built"
  LIBVIRT_IMAGE_SOURCE: "quay.io/ajvictor/podvm-libvirt-upload:v5"
  LIBVIRT_PODVM_IMAGE_PATH: "/image/podvm-s390x.qcow2"
